apply plugin: 'maven-publish'
apply from: "${rootDir}/scripts/versioning.gradle"

afterEvaluate { project ->
    publishing {
        publications {
            release(MavenPublication) {
                groupId = POM_GROUP
                if (isReleaseVersion()) {
                    version = buildVersionName()
                } else {
                    // this makes it possible to specify the master-SNAPSHOT
                    version = gitBranch + "-SNAPSHOT"
                }
                artifactId = POM_ARTIFACT_ID
                from components.release
                pom {
                    name = POM_ARTIFACT_ID
                    description = 'Nabto Edge WebRTC for Android clients.'
                    url = 'https://github.com/nabto/edge-client-android-webrtc'
                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }
                    developers {
                        developer {
                            id = 'nabto'
                            name = 'Nabto'
                            email = 'apps@nabto.com'
                        }
                    }
                    scm {
                        connection = 'scm:git@github.com:nabto/edge-client-android-webrtc.git'
                        developerConnection = 'scm:git@github.com:nabto/edge-client-android-webrtc.git'
                        url = 'https://github.com/nabto/edge-client-android-webrtc'
                    }

                    // The POM checker that JReleaser uses will error without this, see:
                    // https://github.com/jreleaser/jreleaser.github.io/issues/85#issuecomment-3062376973
                    pom.withXml {
                        def buildNode = asNode().appendNode('build')
                        def pluginsNode = buildNode.appendNode('plugins')
                        def pluginNode = pluginsNode.appendNode('plugin')
                        pluginNode.appendNode('groupId', 'com.simpligility.maven.plugins')
                        pluginNode.appendNode('artifactId', 'android-maven-plugin')
                        pluginNode.appendNode('version', '4.6.0')
                        pluginNode.appendNode('extensions', 'true')
                    }
                }
            }
        }

        repositories {
            maven {
                url = rootProject.layout.buildDirectory.dir('staging-deploy')
            }
        }
    }
}
